### ISSUE TITLE
No Data Text appears in a single td without colspan.

### ISSUE THREAD

**Issue by parish-shrestha** [massmutual/react-collapsing-table#102]
Hey, Thank you so much for creating this package. It's really been great.

Here's the issue.

When there's no data in the table, this text "Sorry, your search did not return any results. Please try again." seems to appear in a td without a colspan. Please add the colspan and center the text. Can't add colspan via css. Thanks.

**Comment by Salinn** [comment]
@parish-shrestha if you want to open a pull request and bump the version number I would be happy to take a look and merge it.

**Comment by parish-shrestha** [comment]
> @parish-shrestha if you want to open a pull request and bump the version number I would be happy to take a look and merge it.

Hey, I've created the pull request. Please take a look before merging.

**Comment by Salinn** [comment]
@parish-shrestha Looks good to me, if you bump the package json patch version number I will approve and merge

**Comment by parish-shrestha** [comment]
@Salinn Updated to 1.0.5. Please let me know when you approve and merge.

**Comment by Salinn** [comment]
https://www.npmjs.com/package/react-collapsing-table the new version has been published

**Comment by Salinn** [comment]
Please close this if it fixed your issue =)

**Comment by parish-shrestha** [comment]
Thank you so much !
