### ISSUE TITLE
State on initial render

### ISSUE THREAD

**Issue by snazzypants** [massmutual/react-collapsing-table#41]
When the table first renders, it always puts the data in the same order as the source array.  I am using the `column` and `direction` props but these don't seem to have an effect.  Sorting works just fine after manually sorting on the column of choice.

Also, currentPage does not set page to page of choice.

**Comment by Salinn** [comment]
@snazzypants so the column and direction props are working as designed, we built it thinking that someone may want to say hey we already sorted this by column x in direction y and want the table to do the same. Is this something that you think would be beneficial? 

 I will look at the currentPage bug tomorrow and see if I can recreate it!

**Comment by Salinn** [comment]
@snazzypants currentPage is not setup to change the page, it is actually for displaying the page that you are on. Please let me know if I can make the documentation more clear around [custom pagination](https://github.com/massmutual/react-collapsing-table#custompagination). 

If you want to play with custom pagination some more you can go to the next page by calling `nextPage`, you can go back a page by calling `previousPage` and go to a different page by calling `goToPage`. With `goToPage` you either need to give it a variable called `newPage` like `goToPage({newPage: 1 })` or by letting it be called by an input element like this `<input onChange={ goToPage } onKeyPress={ goToPage } value={ inputtedPage } />` Remember that this component needs to be passed to the table as a prop like `CustomPagination={TextInputPagination}`

I wrote this simple react component to show you how you can go to different pages.

```
import React from 'react';

const TextInputPagination = ({ currentPage, inputtedPage, totalPages, nextPage, previousPage, goToPage }) => {
    const firstPage = <span onClick={ () => goToPage({newPage: 1 }) }>First Page-</span>;
    const previousPageIcon = currentPage > 1 ?
        <span onClick={ previousPage }>-Previous Page-</span> : null;
    const nextPageIcon = currentPage < totalPages ?
        <span onClick={ nextPage }>-Next Page-</span> : null;
    const lastPage = <span onClick={ () => goToPage({newPage: totalPages }) }>-Last Page</span>;

    return(
        <div className="react-collapsible-page">
            <p>
                { firstPage }
                { previousPageIcon }
                Page <input onChange={ goToPage } onKeyPress={ goToPage } value={ inputtedPage } /> of { totalPages }
                { nextPageIcon }
                { lastPage }
            </p>
        </div>
    )
};

export default TextInputPagination
```

**Comment by Salinn** [comment]
Are you still interested in discussing the sorting stuff @snazzypants? If Not I will close this on March 1st

**Comment by snazzypants** [comment]
@Salinn no, that's fine, thanks. Now that I understand better I can just structure my data differently incoming.
