### ISSUE TITLE
CSS includes html tag

### ISSUE THREAD

**Issue by dennisdupont** [massmutual/react-collapsing-table#45]
This becomes problematic for a site-wide CSS reset.  The chances are pretty good that dynamic style elements injected are placed *after* existing ones.  So putting an html element with font in a component specific CSS module will override the inherited definitions for the entire site.  

I would not include a font at all in a styled component, let that be a site decision.

Best would be to package the CSS separate from the js build so any of the component styles can easily be placed and then overridden as a site designer wants.

**Comment by Salinn** [comment]
@paperfox do you have any thoughts on this as you are more of the CSS expert. Thanks!

**Comment by dennisdupont** [comment]
Thanks - no hurries here.

**Comment by Salinn** [comment]
@dennisdupont I am going to close this and let me know if that PR didn't solve your problem.

**Comment by dennisdupont** [comment]
I have not tried it out yet, but from the comments and looking at the code changes, this looks like a great fix.

Sorry for going dark, we are working the back end of our project currently.
