### ISSUE TITLE
Default sort is not per documentation

### ISSUE THREAD

**Issue by dennisdupont** [massmutual/react-collapsing-table#46]
The readme states that the default column to sort on is the first column.  This does not work as the code is using priorityLevel:

```
            column = props.columns.reduce((prev, curr) => {
                return prev.priorityLevel < curr.priorityLevel ? prev : curr;
            }).accessor,
```

But priorityLevel should be used for keeping a column in view as the row is collapsed.  

My use case was to have an Actions column with edit/delete icons in the rightmost position.  Since my view component does not know the table data and schema, I simply was appending a low priority number to ensure that last column stays visible.  Unfortunately that caused my icons to be the default sort.

What is the problem with the approach as documented (use the first column) instead of the priority?  Or make the column option able to take a string (if isNan then treat as the option for handing the default sort)?

Let me know if you want a PR and I'll try and see if I can get my fork working

**Comment by dennisdupont** [comment]
Sorry - just realized that the column option is already a string :(  Should have checked that before inserting foot in mouth.  I suppose another option is to first see if option matches any accessors and if not then evaluate against strings for the default.

**Comment by Salinn** [comment]
@dennisdupont I think I figured out what you meant, why not just say
```
columns = props.columns[0]
```

I think we went with the highest priority based on that is the column you always want to see. @dorward do you have any thoughts on what you think makes the most sense?

Thanks for pointing this out @dennisdupont, either way the docs or the code will get updated.
