### ISSUE TITLE
How to use CustomComponent in cell?

### ISSUE THREAD

**Issue by M4Lien** [massmutual/react-collapsing-table#55]
Hi, I've installed react-collapsing-table in my project. I have to custom one cell with span tag. but I can't get any solution in this documentation. How can I do for this?

**Comment by Salinn** [comment]
Hey @M4Lien please let me know how I can help make this section clearer -> https://github.com/massmutual/react-collapsing-table#add-your-own-components

The basics are you provide your own component and we will pass along all of the information it needs to generate a custom component.

Here is an example.
```
const Button = ({ row, accessor, cellIndex, rowIndex, CustomFunction, }) => {
  return(
    <span>
      { row[accessor] }
      <button onClick={ () => CustomFunction({ rowIndex, cellIndex }) }>send</button>
    </span>
  )
}
export default Button
```

**Comment by Salinn** [comment]
@M4Lien I am going to close this. If you have any other issues let me know!
