### ISSUE TITLE
Uncaught ReferenceError: addSortableToColumns is not defined

### ISSUE THREAD

**Issue by SimmonsRitchie** [massmutual/react-collapsing-table#61]
Hi there, I'm relatively new to React and I was looking for a responsive table for my project. React-collapsing-table seemed very promising but unfortunately I've run into trouble.

When I try to load up my table I'm getting hit with this error:

> Uncaught ReferenceError: addSortableToColumns is not defined
>     at new t (index.js:1)
>     at constructClassInstance (react-dom.development.js:9760)
>     at updateClassComponent (react-dom.development.js:10215)
>     at beginWork (react-dom.development.js:10605)
>     at performUnitOfWork (react-dom.development.js:12573)
>     at workLoop (react-dom.development.js:12682)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
>     at invokeGuardedCallback (react-dom.development.js:1195)
>     at performWork (react-dom.development.js:12800)

I’m using React 16.8 and react-collapsing-table 0.5.1. I tried to follow the example in the docs closely. Here's my code:

```
import React from "react";
import ReactCollapsingTable from "react-collapsing-table";

class ReactCollapsingTableTest extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {

    const rows = [
      { id: 1, firstName: 'Paul', lastName: 'Darragh' }
    ]
    const columns = [
      { accessor: 'firstName', label: 'First Name', priorityLevel: 1, position: 1, minWidth: 150 },
      { accessor: 'lastName', label: 'Last Name', priorityLevel: 2, position: 2, minWidth: 150}
    ]

    return (
      <div>
        <h3>React Collapsing Table</h3>
        <ReactCollapsingTable
          rows={rows}
          columns={columns}
        />
      </div>
    );
  }
}
```
Is this a bug or am I doing something wrong here? Any help would be much appreciated.

**Comment by Salinn** [comment]
Hmm that totally could be a bug. Let me try to recreate this and test it tomorrow. Can you try downgrading to version 0.4.2 and see if you are still seeing the same issue?

**Comment by SimmonsRitchie** [comment]
I just downgraded to 0.4.2 and it seems to be working perfectly now.

Thanks for your work on this package and for the speedy response to this issue, Salinn. I was surprised how hard it was to find a responsive table for React. This looks terrific.

**Comment by hamsteven** [comment]
I'm seeing this same issue. I downgraded to 0.4.2 and still see the error.

**Comment by Salinn** [comment]
@hamsteven thanks for the report? did you run npm i again as it seemed to have worked for @SimmonsRitchie. Either way it needs a fix and something I will get to before June 1st. Thanks for the reminder

**Comment by Salinn** [comment]
@SimmonsRitchie can you try updating to 0.6.0?

**Comment by Salinn** [comment]
Closing as I haven't heard anything in a while about this bug
