### ISSUE TITLE
Dead? Alternative packages?

### ISSUE THREAD

**Issue by thorep** [massmutual/react-collapsing-table#98]
Im looking for collapsing tables for a project im working on. This package seems to do the trick, but its old. Is it maintained? Alternative packages i can use?

**Comment by Salinn** [comment]
Just have not had many feature requests or needs myself that I wanted to change, I have considered trying to convert this to typescript but hasn't been on the top of my list with life. If you find a bug let me know.

**Comment by Salinn** [comment]
Closing as it has been almost 2 months
