### ISSUE TITLE
Support for React 17?

### ISSUE THREAD

**Issue by stellasia** [massmutual/react-collapsing-table#99]
Hi!

I have started using this package with a project under React 16, and now need to migrate to React 17 due to other requirements. Currently getting the following error when trying to install `react-collapsing-table` :

```
$ npm install react-collapsing-table

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.x.x" from react-collapsing-table@1.0.3
npm ERR! node_modules/react-collapsing-table
npm ERR!   react-collapsing-table@"*" from the root project
```

Any solution or plan to upgrade to new versions of React?

**Comment by Salinn** [comment]
Hi Stella,

I have been playing around with updating this package to be more hook and typescript friendly going forward. I am currently tinkering at my job with an internal table and how to provide the best flexibility going forward. I wouldn't expect a major update in the near future, but the change you are looking for is a rather easy one if you want to open a PR for it. To make the change open up the [package.json](https://github.com/massmutual/react-collapsing-table/blob/master/package.json) and update the peerDependencies to look like this
```
"peerDependencies": {
    "react": "^16.x.x" || "^17.x.x"
  },
  ```

**Comment by Salinn** [comment]
@stellasia this version has been pushed https://www.npmjs.com/package/react-collapsing-table

**Comment by Salinn** [comment]
Please close if this solved your issue.

**Comment by stellasia** [comment]
Works perfectly! Thank you very much for the super fast support!
